### ISSUE TITLE
Functions do not deserialize properly.

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/yamlscript#76]
There is a bug in `print()` where the following PS:

```yaml
greet(thing): Hello %($thing)!
greeting:
  $greet: World
```

prints as:

```yaml
greet:
  greet(thing): Hello %($thing)!
greeting: Hello World!
```

It puts the name of the function as a key in the hash, but then repeats it again, whereas it should just put the body.
